Milestone 6 - documentation
aboongm/Capstone_Project pull request #7
Opened 2022-03-16 15:32 UTC by aboongm

- Record a video describing your project.
- Create a good README and pull request description.

2022-03-16 16:44 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED 🔴🟡 🔴 

## Hi @aboongm 👋 

### You are doing a marvelous job on the capstone project and this is one of the best projects I have seen so far!
I really like your presentation for the project 👍

There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- Good commit messages. ✔️

## Required Changes ♻️
- [ ]  In the presentation video you should show some piece of code that you are very proud of, Please make sure your presentation video includes that. (Please also include the presentation video in the PR)
- [ ] Please include project features in more detail in the pull request summary.
- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 16:44 UTC, thecodechaser commented on index.html
>        <header class="m-0 p-0 container">
- [ ] Good job on the design but for this project you are supposed to stick to the [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) template as much as possible.
  - Please place more gap between your menu items and make sure it matches the design on the template.
  - Please remove the background color from your campaign button and place the border as on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/158639927-0b6ba422-ec44-467c-a5ea-6e69fb5bb9c4.png)

## Behnace design

![image](https://user-images.githubusercontent.com/83803414/158640024-7049dd79-1fc9-4382-bd02-22d26e84f3cb.png)

2022-03-16 16:44 UTC, thecodechaser commented on index.html
>            <h3 class="cocogoose text-white text-center h4 fw-bold pt-5">Main Program</h3>
- [x] When we hover the mouse over cards a white border around cards should appear as on the design, Please apply hover effects to your cards so the cards show a white border when we hove mouse over them.

### See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/157689981-91c089cf-d233-49a4-b0d5-3e74f7a6d17b.png)

2022-03-16 16:44 UTC, thecodechaser commented on index.html
>            <h3 class="cocogoose text-white text-center h4 fw-bold pt-5">Main Program</h3>
- [ ] When I see the page on the mobile screen the design is appearing differently for the cards, Please make sure it matches the design on the template for all screens. You may want to reduce the font size.

### Your design

![image](https://user-images.githubusercontent.com/83803414/158641348-7cef5544-ad4e-4a22-bc40-24e35379d55e.png)

### Behance design

![image](https://user-images.githubusercontent.com/83803414/158641397-23e92e6c-fc30-4352-941a-3be115eeb5b5.png)

2022-03-16 16:44 UTC, thecodechaser commented on index.html
>            <h3 class="text-partner text-center h3">Partners</h3>
- [ ] Please increase the size of the partner's image and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/158642005-5043e1f1-06da-4e00-8d4f-1c1e02cd403f.png)

### Behance design

![image](https://user-images.githubusercontent.com/83803414/158642049-22720669-4832-4a45-9a80-f5d45f44b124.png)

2022-03-16 16:44 UTC, thecodechaser commented on index.html
>      <section class="container bg-light p-0 m-0">
- [ ] When I open the mobile menu and switch to the desktop screen the mobile menu is still on the screen it should disappear. Please make sure when we switch the screen from mobile to desktop the mobile menu should disappear.
 - You can use media queries for that if the screen cross the min-width you can set your mobile menu `display: none`

### See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/158642384-1fe15e90-0f29-4d04-8786-06eb79d0290d.png)

2022-03-17 11:13 UTC, AnselemOdims approved these changes
### Hi  @aboongm 🙋‍♀️, 
Good job in making the required changes 👏 
Excellent work on the project.

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 11:15 UTC, merged